### ISSUE TITLE
Prototype a DAP version scan 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#875] opened 2024-03-21 18:32 UTC
Example of where the version number is found:  

> https://github.com/digital-analytics-program/gov-wide-code/blob/d9b51e823219b00739da06055ff609bcafd619f2/Universal-Federated-Analytics.js#L24

`    VERSION: "20240524 v7.05 - Dual Tracking",`

The data field should be the version itself, or some appropriate string.  Maybe what is in the quotation marks?  

field id: dap_version
When we're done, it'll go after dap parameters and before third party services

**Comment by gbinal** [comment] 2024-08-14 18:08
This is planned out and ready for scanning in production.  Let's go ahead and do that.  Good work, @luke-at-flexion !!

**Comment by luke-at-flexion** [comment] 2024-08-19 20:21
This work is functionally complete. The test failures in the CI pipeline were unexpected, though, and I am consulting with Andy to see how best to clear them. To my knowledge, the failures were not caused by my work.

**Comment by luke-at-flexion** [comment] 2024-08-20 20:01
All test failures have been fixed and everything has been merged. This should be 100%

**Comment by gbinal** [comment] 2024-08-26 17:44
Alright - I've checked out the initial data **and it looks great**!  

@luke-at-flexion - thanks for getting this one done so handily.  Let's go ahead and make that field live in production, in the snapshots and in the API.  Woot!

**Closed** 2024-09-04 16:24 UTC
